# Generated by Django 4.2.8 on 2024-01-14 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poultry_b', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenFigures_b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_rank', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('chicken_in', models.IntegerField(blank=True, default=0, null=True)),
                ('chicken_out', models.IntegerField(blank=True, default=0, null=True)),
                ('chicken_mortality', models.IntegerField(blank=True, default=0, null=True)),
                ('chicken_slaughtered', models.IntegerField(blank=True, default=0, null=True)),
                ('chicken_out_kilogram', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('chicken_out_unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('chicken_out_total_cost', models.IntegerField(blank=True, default=0, null=True)),
                ('total_chicken', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
