# Generated by Django 4.2.8 on 2024-04-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry_b', '0005_customerrank_b_profit_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickenfigures_b',
            name='chicken_out_kilogram',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
