from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

urlpatterns = [
    path('batch/', views.batch, name='batch'),
    path('index/', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('register/', views.register, name='register'),
    path('chicken/', views.chicken, name='chicken'),
    path('chickens_out/', views.chickens_out, name='chickens_out'),
    path('chickens_slaughtered/', views.chickens_slaughtered, name='chickens_slaughtered'),
    path('chickens_mortality/', views.chickens_mortality, name='chickens_mortality'),
    path('feed/', views.feed, name='feed'),
    path('feed_overview/', views.feed_overview, name='feed_overview'),
    path('drugs/', views.drugs, name='drugs'),
    path('drugs_overview/', views.drugs_overview, name='drugs_overview'),
    path('delete_drugs/<int:id>/', views.delete_drugs, name='delete_drugs'),
    path('necessities/', views.necessities, name='necessities'),
    path('necessities_overview/', views.necessities_overview, name='necessities_overview'),
    path('coldroom_in/', views.coldroom_in, name='coldroom_in'),
    path('total_coldroom/', views.total_coldroom, name='total_coldroom'),
    path('production/', views.production, name='production'),
    path('delete_production/<int:id>/', views.delete_production, name='delete_production'),
    path('', auth_view.LoginView.as_view(template_name='poultry/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='poultry/logout.html'), name='logout'),
    path('delete_models/', views.delete_models, name='delete_models'),
    path('update_chicken/<int:id>/', views.update_chicken, name='update_chicken'),
    path('delete_chicken/<int:id>/', views.delete_chicken, name='delete_chicken'),
    path('update_chicken_out/<int:id>/', views.update_chicken_out, name='update_chicken_out'),
    path('update_drugs/<int:id>/', views.update_drugs, name='update_drugs'),
    path('update_feed/<int:id>/', views.update_feed, name='update_feed'),
    path('update_production/<int:id>/', views.update_production, name='update_production'),
    path('update_necessities/<int:id>/', views.update_necessities, name='update_necessities'),
    path('imprest/', views.imprest, name='imprest'),
    path('total_imprest/', views.total_imprest, name='total_imprest'),
    path('notepad/', views.notepad, name='notepad'),
    path('notepad_detail/<int:id>/', views.notepad_detail, name='notepad_detail'),
    path('notepad_delete/<int:id>/', views.notepad_delete, name='notepad_delete'),
    path('notepad_overview/', views.notepad_overview, name='notepad_overview'),
    path('offals/', views.offals, name='offals'),
    path('offals_overview/', views.offals_overview, name='offals_overview'),
]
