# Generated by Django 4.2.8 on 2023-12-24 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_chicken', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChickenFigures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chicken_in', models.IntegerField(default=0)),
                ('chicken_out', models.IntegerField(default=0)),
                ('chicken_mortality', models.IntegerField(default=0)),
                ('chicken_slaughtered', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_chicken', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='poultry.chickendetails')),
            ],
        ),
    ]
