# Generated by Django 4.2.8 on 2023-12-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0002_alter_chickenfigures_total_chicken'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickenfigures',
            name='chicken_out_kilogram',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='chickenfigures',
            name='chicken_out_total_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chickenfigures',
            name='chicken_out_unit_price',
            field=models.IntegerField(default=0),
        ),
    ]
