# Generated by Django 4.2.8 on 2023-12-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0004_alter_chickenfigures_chicken_out_kilogram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickenfigures',
            name='total_chicken',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
