# Generated by Django 4.2.8 on 2023-12-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0005_alter_chickenfigures_total_chicken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickenfigures',
            name='chicken_in',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chickenfigures',
            name='chicken_mortality',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chickenfigures',
            name='chicken_out',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chickenfigures',
            name='chicken_slaughtered',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
