# Generated by Django 4.2.8 on 2023-12-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0008_alter_chickenfigures_chicken_out_kilogram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickenfigures',
            name='chicken_out_kilogram',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
