# Generated by Django 4.2.8 on 2023-12-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0009_alter_chickenfigures_chicken_out_kilogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_description', models.CharField(max_length=100)),
                ('feed_quantity', models.IntegerField(blank=True, null=True)),
                ('feed_cost', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
