# Generated by Django 4.2.8 on 2023-12-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0010_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
