# Generated by Django 4.2.8 on 2023-12-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0011_feed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_description', models.CharField(max_length=100)),
                ('drug_cost', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
