# Generated by Django 4.2.8 on 2023-12-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0012_drugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
