# Generated by Django 4.2.8 on 2023-12-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0015_coldroomin_coldroomout'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldroomin',
            name='total_coldroom',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
