# Generated by Django 4.2.8 on 2023-12-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0016_coldroomin_total_coldroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickenfigures',
            name='customer',
            field=models.CharField(default="Add Customer's name", max_length=100),
        ),
    ]
