# Generated by Django 4.2.8 on 2023-12-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0018_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(blank=True, null=True)),
                ('expenditure', models.IntegerField(blank=True, null=True)),
                ('calculate', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
