# Generated by Django 4.2.8 on 2024-01-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0020_alter_profit_calculate_alter_profit_expenditure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
