# Generated by Django 4.2.8 on 2024-01-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0023_alter_chickenfigures_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickenfigures',
            name='customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
