# Generated by Django 4.2.8 on 2024-01-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0024_alter_chickenfigures_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='production_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
