# Generated by Django 4.2.8 on 2024-01-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0025_alter_production_production_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='drug_cost',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feed_cost',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='necessities',
            name='necessities_cost',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='production_cost',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
