# Generated by Django 4.2.8 on 2024-01-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0028_alter_chickenfigures_chicken_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickenfigures',
            name='chicken_in',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chickenfigures',
            name='chicken_mortality',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chickenfigures',
            name='chicken_out',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chickenfigures',
            name='chicken_out_total_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chickenfigures',
            name='chicken_out_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chickenfigures',
            name='chicken_slaughtered',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chickenfigures',
            name='total_chicken',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='drug_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feed_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='necessities',
            name='necessities_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='production_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
