# Generated by Django 4.2.8 on 2024-01-03 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0030_customerrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerrating',
            old_name='customer',
            new_name='client',
        ),
    ]
