# Generated by Django 4.2.8 on 2024-01-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0034_alter_chickenfigures_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrating',
            name='customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
