# Generated by Django 4.2.8 on 2024-01-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0037_chickenfigures_customer_rank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerRating',
            new_name='CustomerRank',
        ),
        migrations.RenameField(
            model_name='customerrank',
            old_name='customer_rank',
            new_name='customer_rk',
        ),
    ]
