# Generated by Django 4.2.8 on 2024-01-08 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0040_imprest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imprest',
            name='user',
        ),
    ]
