# Generated by Django 4.2.8 on 2024-01-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0043_alter_notepad_note_alter_notepad_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offals_description', models.CharField(max_length=100)),
                ('offals_cost', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
