# Generated by Django 4.2.8 on 2024-01-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0044_offals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coldroomin',
            name='chickens_in_freezer',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
