# Generated by Django 4.2.8 on 2024-01-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0047_alter_imprest_imprest'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprest',
            name='total_imprest',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='imprest',
            name='imprest',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
