# Generated by Django 4.2.8 on 2024-03-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0048_imprest_total_imprest_alter_imprest_imprest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickenfigures',
            name='chicken_out_kilogram',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
